version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: movies  
    ports:
      - "8080:8080"
    volumes:
      - ./src:/go/src/github.com/santa512/monorepo-microservices/src
      - ./config:/go/src/github.com/santa512/monorepo-microservices/config
      - ./.air.toml:/root/.air.toml
